import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import StoreProvider from "@/components/providers/StoreProvider";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import { getUserLoaction } from "@/hooks/getUserLocation";
import SessionWrapper from "@/components/providers/SessionWrapper";
import { auth } from "../../auth";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userFlag = await getUserLoaction();
  const user = await auth()
console.log(user)
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StoreProvider>
          <SessionWrapper>
            <Header flag={userFlag.emojitwo} />
            {children}
            <Footer />
          </SessionWrapper>
        </StoreProvider>
      </body>
    </html>
  );
}
